name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 0 * * *"  # Atualiza todo dia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
      - name: Gera a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: britojulia
          outputs: dist/github-contribution-grid-snake.svg
      - name: Publica a cobrinha
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
